import Head from "next/head"
import styles from "../../styles/Home.module.css"
import { createUrqlClient } from "../../src/utils/createUrqlClient"
import { withUrqlClient } from "next-urql"
import { useLocationsQuery, useUpdateVisibilityMutation, useUpdateComingSoonMutation } from "../../src/generated/graphql"
import { Fragment, useState} from "react"
import Link from 'next/link'
import { Button, useToast,
   Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
    useDisclosure } from "@chakra-ui/react"
import axios from "axios"

import ConfirmationModal from '../../src/components/ConfirmationModal'

const Locations = () => {
  const toast = useToast()
  // const router = useRouter()

  const [isVisible, setVisible] = useUpdateVisibilityMutation()
  const [comingSoon, setComingSoon] = useUpdateComingSoonMutation()
  const [{ data, fetching }, updateLocations] = useLocationsQuery()
  const { isOpen, onOpen, onClose } = useDisclosure()

  const [deleteLocationId, setDeleteLocationId] = useState("")
  if (!fetching && data.locations) {
    data.locations.map((location) => {
      Object.keys(location).forEach((key) => {
        try {
          location[key] = JSON.parse(location[key])
        } catch {
          location[key] = location[key]
        }
      })
    })
  }
  async function toggleLocationVisible(id, visible) {
    setVisible({
      input: {
        visible: visible,
        yextId: id,
      },
    })
    data.locations.find((location) => location.yextId === id).visible = visible
  }

  async function toggleComingSoon(id, comingSoon) {
    setComingSoon({
      input: {
        comingSoon,
        yextId: id,
      },
    })
    data.locations.find((location) => location.yextId === id).comingSoon = comingSoon
  }
  async function deleteLocation() {
    const result = await axios.delete(`http://localhost:4000/hooks/yext/${deleteLocationId}`)
    console.log('result', result)
    toast({
      duration: null,
      position: 'top-right',
      title: `${result.data.message || 'Success'}`,
      status: (result.data.type == 'FATAL_ERROR') ? 'error' : 'success',
      isClosable: true,
    })
    updateLocations
  }

  function showDeleteModal(id){
    onOpen()
    setDeleteLocationId(id)

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Modal Title</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            Are you sure you want to delete this location?
          </ModalBody>

          <ModalFooter>
            <Button colorScheme='red' mr={3} onClick={deleteLocation}>
              Yes
            </Button>
            <Button variant='ghost' onClick={onClose}>no</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>      <main className={styles.main}>
        <Button><Link href={'/locations/add'}>Add Location</Link></Button>
        <table>
          <thead>
            <tr>
              <td>Name</td>
              <td>Address</td>
              <td>Is Visible</td>
              <td>Is coming soon</td>
              <td>Delete</td>
            </tr>
          </thead>
          <tbody>
            {!fetching && data && data.locations
              ? data.locations.map((location) => (
                  <tr key={location.id}>
                    <td>
                      <a href={`/locations/${location.c_locationSlug}`}>{location.c_locationName}</a>
                    </td>
                    <td>{location.address.line1} {location.address.city}, {location.address.region}</td>
                    <td>
                      <input type="checkbox" name="visible" checked={location.visible} onChange={() => toggleLocationVisible(location.yextId, !location.visible)} />
                    </td>
                    <td>
                    <input type="checkbox" name="comingSoon" checked={location.comingSoon} onChange={() => toggleComingSoon(location.yextId, !location.comingSoon)} />
                    </td>
                    <td>
                      <Button onClick={() => showDeleteModal(location.c_locationSlug)}>Delete</Button>
                    </td>
                  </tr>
                ))
              : null}
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default withUrqlClient(createUrqlClient, { ssr: false })(Locations)
